### ISSUE TITLE
Поле Напомена / Note не сохраняется в PDF

### ISSUE THREAD

**Issue by slabstone** [Antiokh/antiokh.github.io#4]
При нажатии на кнопку "Сохранить PDF" в полученном PDF-файле поле Напомена / Note пустое, даже если в HTML-форме оно заполнено.

![image](https://github.com/user-attachments/assets/bf99e81d-71fd-4184-8464-41cfec602c9d)

**Comment by Antiokh** [comment]
Да, всё правильно, это поле используется только самими полицейскими и не печатается. Ошибки нет.
